#!/usr/bin/env bash
# This script parses the /etc/passwd file and displays information in a story-like format

while IFS=: read user x uid gid home dir shell; do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $user"
done < /etc/passwd
