#!/usr/bin/env bash
# This script extracts and sorts unique hostnames from apache-access.log

if [[ ! -f "apache-access.log" ]]; then
  echo "Log file apache-access.log not found!"
  exit 1
fi

awk '{print $1}' apache-access.log | sort -u
